dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
networks:
  default: development
  development:
    verify: False
  sepolia:
    verify: True
    weth_token: '0xD0dF82dE051244f04BfF3A8bB1f62E1cD39eED92'
    otk_token: '0x3F2BbEe309aB718Ff17B7c251C3C3CC1889EB405'
    dai_usd_price_feed: '0x14866185B1962B63C3Ea9E03Bc1da838bab34C19'
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
  goerli:
    verify: True
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
    fau_token: '0xBA62BCfcAaFc6622853cca2BE6Ac7d845BC0f2Dc'
    dai_usd_price_feed: '0x0d79df66BE487753B02D015Fb622DED7f0E9798d'
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
wallets:
  from_key: ${PRIVATE_KEY}